In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/netflix_titles (3).csv")

In [ ]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [ ]:
df.shape

(8807, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [ ]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [ ]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [ ]:
df.director.fillna ("unknown", inplace =True)

/tmp/ipython-input-3845408888.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.director.fillna ("unknown", inplace =True)

In [ ]:
df.country.fillna ("unknown", inplace =True)

/tmp/ipython-input-3355673291.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.country.fillna ("unknown", inplace =True)

In [ ]:
df.cast.fillna ("unknown", inplace =True)

/tmp/ipython-input-955799205.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.cast.fillna ("unknown", inplace =True)

In [ ]:
df[df['date_added'].isnull()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6066,s6067,TV Show,A Young Doctor's Notebook and Other Stories,unknown,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6174,s6175,TV Show,Anthony Bourdain: Parts Unknown,unknown,Anthony Bourdain,United States,NaN,2018,TV-PG,5 Seasons,Docuseries,This CNN original series has chef Anthony Bour...
6795,s6796,TV Show,Frasier,unknown,"Kelsey Grammer, Jane Leeves, David Hyde Pierce...",United States,NaN,2003,TV-PG,11 Seasons,"Classic & Cult TV, TV Comedies",Frasier Crane is a snooty but lovable Seattle ...
6806,s6807,TV Show,Friends,unknown,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...
6901,s6902,TV Show,Gunslinger Girl,unknown,"Yuuka Nanri, Kanako Mitsuhashi, Eri Sendai, Am...",Japan,NaN,2008,TV-14,2 Seasons,"Anime Series, Crime TV Shows","On the surface, the Social Welfare Agency appe..."
7196,s7197,TV Show,Kikoriki,unknown,Igor Dmitriev,unknown,NaN,2010,TV-Y,2 Seasons,Kids' TV,A wacky rabbit and his gang of animal pals hav...
7254,s7255,TV Show,La Familia P. Luche,unknown,"Eugenio Derbez, Consuelo Duval, Luis Manuel Áv...",United States,NaN,2012,TV-14,3 Seasons,"International TV Shows, Spanish-Language TV Sh...","This irreverent sitcom featues Ludovico, Feder..."
7406,s7407,TV Show,Maron,unknown,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
7847,s7848,TV Show,Red vs. Blue,unknown,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
8182,s8183,TV Show,The Adventures of Figaro Pho,unknown,"Luke Jurevicius, Craig Behenna, Charlotte Haml...",Australia,NaN,2015,TV-Y7,2 Seasons,"Kids' TV, TV Comedies","Imagine your worst fears, then multiply them: ..."

In [ ]:

df.loc[6066, "date_added"] = "october 2,2013"
df.loc[6174, "date_added"] = "April 14, 2013"
df.loc[6795, "date_added"] = "january 15, 1993"
df.loc[6806, "date_added"] = "September 22, 1994"
df.loc[6901, "date_added"] = "july 23, 2003"
df.loc[7196, "date_added"] = "august 14, 2004"
df.loc[7254, "date_added"] = "october 5, 2002"
df.loc[7406, "date_added"] = "May 3, 2013"
df.loc[7847, "date_added"] = "june 18, 2003"
df.loc[8182, "date_added"] = "may 13, 2012"

In [ ]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          4
duration        3
listed_in       0
description     0
dtype: int64

In [ ]:
df.duration.fillna(df.rating,inplace = True)

/tmp/ipython-input-1250184991.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.duration.fillna(df.rating,inplace = True)

In [ ]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          4
duration        0
listed_in       0
description     0
dtype: int64

In [ ]:
df[df['rating'].isnull()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5989,s5990,Movie,13TH: A Conversation with Oprah Winfrey & Ava ...,unknown,"Oprah Winfrey, Ava DuVernay",unknown,"January 26, 2017",2017,NaN,37 min,Movies,Oprah Winfrey sits down with director Ava DuVe...
6827,s6828,TV Show,Gargantia on the Verdurous Planet,unknown,"Kaito Ishikawa, Hisako Kanemoto, Ai Kayano, Ka...",Japan,"December 1, 2016",2013,NaN,1 Season,"Anime Series, International TV Shows","After falling through a wormhole, a space-dwel..."
7312,s7313,TV Show,Little Lunch,unknown,"Flynn Curry, Olivia Deeble, Madison Lu, Oisín ...",Australia,"February 1, 2018",2015,NaN,1 Season,"Kids' TV, TV Comedies","Adopting a child's perspective, this show take..."
7537,s7538,Movie,My Honor Was Loyalty,Alessandro Pepe,"Leone Frisa, Paolo Vaccarino, Francesco Miglio...",Italy,"March 1, 2017",2015,NaN,115 min,Dramas,"Amid the chaos and horror of World War II, a c..."

In [ ]:
df.loc[5989, "rating"] = "TV-PG"
df.loc[6827, "rating"] = "TV-14"
df.loc[7312, "rating"] = "TV-PG"
df.loc[7537, "rating"] = "PG-13"

In [ ]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [ ]:
# first question
df.listed_in = df.listed_in.str.split(',').str[0]

In [ ]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,unknown,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,International TV Shows,"After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",unknown,"September 24, 2021",2021,TV-MA,1 Season,Crime TV Shows,To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,unknown,unknown,unknown,"September 24, 2021",2021,TV-MA,1 Season,Docuseries,"Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,International TV Shows,In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,Cult Movies,"A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,unknown,unknown,unknown,"July 1, 2019",2018,TV-Y7,2 Seasons,Kids' TV,"While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,Comedies,Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,Children & Family Movies,"Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,Dramas,A scrappy but poor boy worms his way into a ty...

In [ ]:
a =df.listed_in.value_counts().reset_index()

In [ ]:
a

                       listed_in  count
0                         Dramas   1600
1                       Comedies   1210
2             Action & Adventure    859
3                  Documentaries    829
4         International TV Shows    774
5       Children & Family Movies    605
6                 Crime TV Shows    399
7                       Kids' TV    388
8                Stand-Up Comedy    334
9                  Horror Movies    275
10              British TV Shows    253
11                    Docuseries    221
12                  Anime Series    176
13          International Movies    128
14                   TV Comedies    120
15                    Reality TV    120
16                Classic Movies     80
17                     TV Dramas     67
18                     Thrillers     65
19                        Movies     57
20         TV Action & Adventure     40
21  Stand-Up Comedy & Talk Shows     34
22             Romantic TV Shows     32
23             Classic & Cult TV     22
24                Anime Features     21
25            Independent Movies     20
26              Music & Musicals     18
27                      TV Shows     16
28              Sci-Fi & Fantasy     13
29                   Cult Movies     12
30                     TV Horror     11
31               Romantic Movies      3
32     Spanish-Language TV Shows      2
33                  LGBTQ Movies      1
34           TV Sci-Fi & Fantasy      1
35                 Sports Movies      1

In [ ]:
import plotly.express as px

In [ ]:
# TASK:-4 CREATE VISUALIZATIONS TO REPRESENT THE DISTRIBUTION OF CONTENT OVER DIFFERENT GENRES.
import plotly.express as px
px.bar(a,
       x = "listed_in",
       y = "count",
       color = "listed_in",labels = {"listed_in": "genres",
       "count":"content"},
       title = "distribution of content over different genres")

In [ ]:
# second question
b =df.release_year.value_counts().reset_index()

In [ ]:
b

    release_year  count
0           2018   1147
1           2017   1032
2           2019   1030
3           2020    953
4           2016    902
..           ...    ...
69          1961      1
70          1925      1
71          1959      1
72          1966      1
73          1947      1

[74 rows x 2 columns]

In [ ]:
# TASK 5 :- Visualize the distribution of content across release years.
import plotly.express as px
px.scatter(b, x='release_year', y="count",
           labels = {"release_year": "release year","count":
           "count of content"},title = " distribution of content across release years")

In [ ]:
df.country = df.country.str.split(',').str[0]

In [ ]:
# third question
c = df.country.value_counts().reset_index()

In [ ]:
c

           country  count
0    United States   3211
1            India   1008
2          unknown    831
3   United Kingdom    628
4           Canada    271
..             ...    ...
82    West Germany      1
83        Slovenia      1
84       Guatemala      1
85         Jamaica      1
86         Somalia      1

[87 rows x 2 columns]

In [ ]:
# task 6 :- Explore the geographical distribution of content (if applicable).
c= px.choropleth(c,locations= c["country"],locationmode="country names",
                 projection = "orthographic",color = c['count'],title=
                 " geographical distribution of content")

In [ ]:
c

In [ ]:
# fourth question
df['date_added'] = pd.to_datetime(df['date_added'], format='mixed')
df['month_name'] = df['date_added'].dt.month_name()

In [ ]:
df["month_name"]
month_order = [
    'January','February','March','April','May','June',
    'July','August','September','October','November','December']

In [ ]:
df['month_name'] = pd.Categorical(
    df['month_name'],
    categories=month_order,
    ordered=True)
d = df.month_name.value_counts().sort_index().reset_index()

In [ ]:
# TASK 7 :- IF THERE'S A TEMPORAL COMPONENT, PERFORM TIME SERIES ANALYSIS TO IDENTIFY TRENDS AND PATTERNS OVERTIME.
import plotly.express as px
px.bar(d,
    x='month_name',
    y='count',
    title='Number of Netflix Titles Added per Month',
    labels={'month': 'Months', 'count': 'Number of Titles',},color = "count")

In [ ]:
# fifth question
e =df.rating.value_counts().reset_index()

In [ ]:
e

      rating  count
0      TV-MA   3207
1      TV-14   2161
2      TV-PG    865
3          R    799
4      PG-13    491
5      TV-Y7    334
6       TV-Y    307
7         PG    287
8       TV-G    220
9         NR     80
10         G     41
11  TV-Y7-FV      6
12     NC-17      3
13        UR      3
14    74 min      1
15    84 min      1
16    66 min      1

In [ ]:
# TASK 8 :- ANALYZE THE DISTRIBUTION OF CONTENT RATINGS.
import plotly.express as px
px.line(e, x= "rating",y = "count",
labels = {"count":"content"},
        title = " distribution of content ratings")

In [ ]:
# sixth question
movies = df[df["type"] == "Movie"].copy()
movies["duration_min"] = movies["duration"].str.replace(" min", "").astype(int)
movies["date_added"] = pd.to_datetime(movies["date_added"])
avg_duration = ( movies.set_index("date_added").resample("YE")["duration_min"].mean())

In [ ]:
f = (movies.set_index("date_added").resample("YE")["duration_min"].mean().reset_index())

In [ ]:
f

   date_added  duration_min
0  2008-12-31     81.000000
1  2009-12-31     66.500000
2  2010-12-31     84.000000
3  2011-12-31     93.461538
4  2012-12-31     62.000000
5  2013-12-31     83.500000
6  2014-12-31     77.000000
7  2015-12-31     83.571429
8  2016-12-31     83.545455
9  2017-12-31     95.654350
10 2018-12-31    101.739693
11 2019-12-31     99.923455
12 2020-12-31    101.585670
13 2021-12-31    102.839879

In [ ]:
# TASK 9 :- EXPLORE THE LENGTH OF MOVIES OR EPISODES AND IDENTIFY ANY TRENDS.
import plotly.express as px
px.scatter(f, x="date_added", y="duration_min",
    title="Average Movie Duration on Netflix per Year",
    labels={"date_added": "Year",
        "duration_min": "Average Duration (minutes)" },color = "duration_min")

In [ ]:
# seventh question
g =df.rating.value_counts().reset_index()

In [ ]:
g

      rating  count
0      TV-MA   3207
1      TV-14   2161
2      TV-PG    865
3          R    799
4      PG-13    491
5      TV-Y7    334
6       TV-Y    307
7         PG    287
8       TV-G    220
9         NR     80
10         G     41
11  TV-Y7-FV      6
12     NC-17      3
13        UR      3
14    74 min      1
15    84 min      1
16    66 min      1

In [ ]:
# TASK 10 :- IDENTIFY AND PRESENT TOP-RATED MOVIES OR TV SHOWS BASED ON USER RATINGS.
import plotly.express as px
px.histogram(g.head(10),x="rating",y="count",
    title="Top Rated Movies On Netflix ",
    labels={"count": "Number of Titles", "rating": "Rating"})

In [ ]:
# eighth question
df['date_added'] = pd.to_datetime(df['date_added'], format='mixed')
df['year_added'] = df['date_added'].dt.year
df.listed_in = df.listed_in.str.split(',').str[0]

In [ ]:
h = (df.groupby(['year_added', 'listed_in']).size().reset_index(name='count'))

In [ ]:
# TASK 11 :- ANALYZE TRENDS IN THE POPULARITY OF DIFFERENT GENRES OVER TIME.
import plotly.express as px
px.line(h.head(10),
    x='year_added',
    y='listed_in',labels = {"year_added": "years", "listed_in": "genres"},
    title='Trends in Popularity of Netflix Genres Over Time')

In [ ]:
# ninth question
df.country = df.country.str.split(',').str[0]

In [ ]:
i =df.country.value_counts().reset_index()

In [ ]:
# TASK 12 :- FURTHER EXPLORE THE DISTRIBUTION OF CONTENT ACROSS DIFFERENT COUNTRIES AND REGIONS.
import plotly.express as px
px.choropleth(i,locations= i["country"],locationmode="country names",
              projection = "natural earth",color = i['count'])

In [ ]:
# tenth question
movies = df[df["type"] == "Movie"].copy()
movies["duration_min"] = movies["duration"].str.replace(" min", "").astype(int)

In [ ]:
df["rating"].unique()

array(['PG-13', 'TV-MA', 'PG', 'TV-14', 'TV-PG', 'TV-Y', 'TV-Y7', 'R',
       'TV-G', 'G', 'NC-17', '74 min', '84 min', '66 min', 'NR',
       'TV-Y7-FV', 'UR'], dtype=object)

In [ ]:
rating_order = {
    'G': 1,
    'PG': 2,
    'PG-13': 3,
    'R': 4,
    'NC-17': 5,
    'TV-Y': 1,
    'TV-Y7': 2,
    'TV-G': 2,
    'TV-PG': 3,
    'TV-14': 4,
    'TV-MA': 5}

j = movies['rating_numeric'] = movies['rating'].map(rating_order)

In [ ]:
# TASK 13 :- INVESTIGATE POTENTIAL CORRELATIONS BETWEEN VARIABLES (E.G., RATINGS AND DURATION).
import plotly.express as px
px.box(movies,x='rating_numeric',y='duration_min',
    title='Distribution of Movie Duration Across Ratings',color = "rating_numeric")

In [ ]:
# thirteenth question
df.listed_in = df.listed_in.str.split(',').str[0]

In [ ]:
k = df.listed_in.value_counts().reset_index()

In [ ]:
k

                       listed_in  count
0                         Dramas   1600
1                       Comedies   1210
2             Action & Adventure    859
3                  Documentaries    829
4         International TV Shows    774
5       Children & Family Movies    605
6                 Crime TV Shows    399
7                       Kids' TV    388
8                Stand-Up Comedy    334
9                  Horror Movies    275
10              British TV Shows    253
11                    Docuseries    221
12                  Anime Series    176
13          International Movies    128
14                   TV Comedies    120
15                    Reality TV    120
16                Classic Movies     80
17                     TV Dramas     67
18                     Thrillers     65
19                        Movies     57
20         TV Action & Adventure     40
21  Stand-Up Comedy & Talk Shows     34
22             Romantic TV Shows     32
23             Classic & Cult TV     22
24                Anime Features     21
25            Independent Movies     20
26              Music & Musicals     18
27                      TV Shows     16
28              Sci-Fi & Fantasy     13
29                   Cult Movies     12
30                     TV Horror     11
31               Romantic Movies      3
32     Spanish-Language TV Shows      2
33                  LGBTQ Movies      1
34           TV Sci-Fi & Fantasy      1
35                 Sports Movies      1

In [ ]:
# TASK 14 :- EVALUATE THE DIVERSITY OF CONTENT BY ANALYZING THE NUMBER OF UNIQUE GENRES AND CATEGORIES.
import plotly.express as px
px.histogram(k.head(10),x='listed_in',y='count',color = "listed_in",
             labels = {"listed_in": " genres"},
    title='Top 10 unique Genres by Number of Netflix Titles')

In [ ]:
category_counts = (df['type'].value_counts().reset_index())
category_counts.columns = ['type', 'count']

In [ ]:
# TASK 14 :- EVALUATE THE DIVERSITY OF CONTENT BY ANALYZING THE NUMBER OF UNIQUE GENRES AND CATEGORIES.
import plotly.express as px
px.pie(category_counts,names='type',values='count',
    title='Distribution of Content Categories on Netflix')

In [ ]:
movies = df[df["type"] == "Movie"].copy()
movies["duration_min"] = movies["duration"].str.replace(" min", "").astype(int)
movies["date_added"] = pd.to_datetime(movies["date_added"])
df['year_added'] = df['date_added'].dt.year

In [ ]:
M= (movies.groupby('year_added')['duration_min'].mean().reset_index())

In [ ]:
M

    year_added  duration_min
0         2008     81.000000
1         2009     66.500000
2         2010     84.000000
3         2011     93.461538
4         2012     62.000000
5         2013     83.500000
6         2014     77.000000
7         2015     83.571429
8         2016     83.545455
9         2017     95.654350
10        2018    101.739693
11        2019     99.923455
12        2020    101.585670
13        2021    102.839879

In [ ]:
# TASK 15 :- EXPLORE HOW THE CHARACTERISTICS OF CONTENT (E.G., DURATION, RATINGS) HAVE EVOLVED OVER THE YEARS.
import plotly.express as px
px.line(M,x='year_added',y='duration_min',
        labels = {"year_added" : "years"},
    title='Average Duration of Netflix Movies Over Time')

In [ ]:
rating_trend = (df.groupby(['year_added', 'rating']).size().reset_index(name='count'))

In [ ]:
# # TASK 15 :- EXPLORE HOW THE CHARACTERISTICS OF CONTENT (E.G., DURATION, RATINGS) HAVE EVOLVED OVER THE YEARS.
import plotly.express as px
px.bar(rating_trend,
    x='year_added',
    y='count',
    color='rating',
    title='Evolution of Content Ratings on Netflix Over Time')